#!/bin/sh

XRES="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
[[ -f $XRES ]] && xrdb -merge -I$HOME $XRES

#[[ -f ~/.xmodmap ]] && xmodmap ~/.xmodmap

# xset +fp $HOME/.local/share/fonts
# xset fp rehash

xset r rate 190 90 &

$HOME/.screenlayout/2-monitor.sh &
#picom -b --config $HOME/.config/picom.conf --dbus --experimental-backends &
# setbg &
#xwallpaper --zoom $HOME/img/wallpaper/pills-grey3.v.jpg

#xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
#setbg &			# set the background with the `setbg` script
#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
#remaps &		# run the remaps script, switching caps/esc and more; check it for more info

#autostart="mpd xcompmgr dunst unclutter pipewire"
autostart="sxhkd"
for program in $autostart; do
    pidof -s "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"

