#!/bin/sh

XRES="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources"
[ -f "$XRES" ] && xrdb -merge -I"$HOME" "$XRES"

XMODMAP="${XDG_CONFIG_HOME:-$HOME/.config}/x11/xmodmap"
[ -f "$XMODMAP" ] && xmodmap "$XMODMAP"

"$HOME/.screenlayout/2-monitor.sh" &

# xset +fp $HOME/.local/share/fonts
# xset fp rehash

hsetroot -solid '#101010'
nitrogen --restore

picom -b --config "$HOME/.config/picom.conf" --dbus

#autostart="mpd xcompmgr dunst unclutter pipewire"
#autostart="sxhkd"
# autostart="pipewire"
# for program in $autostart; do
#     pidof -s "$program" || "$program" &
# done >/dev/null 2>&1

xset r rate 190 90

[ -n "$xrdbpid" ] && wait "$xrdbpid"

