#!/bin/sh
if [[ $TERM = "xterm-kitty" ]]; then
    kitty +icat --clear --silent --transfer-mode file
elif [ -n "$FIFO_UEBERZUG" ]; then
	printf '{"action": "remove", "identifier": "PREVIEW"}\n' > "$FIFO_UEBERZUG"
fi
