#!/bin/sh

set -C -f
IFS="$(printf '%b_' '\n')"; IFS="${IFS%_}"

image() {
	if [ -f "$1" ] && [ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1; then
		printf '{"action": "add", "identifier": "PREVIEW", "x": "%s", "y": "%s", "width": "%s", "height": "%s", "scaler": "contain", "path": "%s"}\n' "$4" "$5" "$(($2-1))" "$(($3-1))" "$1" > "$FIFO_UEBERZUG"
	else
		mediainfo "$6"
	fi
}

batorcat() {
	file="$1"
	shift
    if command -v bat > /dev/null 2>&1
    then
        #bat --color=always --style=plain --pager=never "$file" "$@"
        bat --color=always --style=full --pager=never --theme "$COLORTHEME" "$file" "$@"
    else
        cat "$file"
    fi
}

ifub() {
	[ -n "$DISPLAY" ] && [ -z "$WAYLAND_DISPLAY" ] && command -V ueberzug >/dev/null 2>&1
}

CACHE="$HOME/.cache/lf/thumbnail.$(stat --printf '%n\0%i\0%F\0%s\0%W\0%Y' -- "$(readlink -f "$1")" | sha256sum | awk '{print $1}'))"

#case "$(file --dereference --brief --mime-type -- "$1")" in
case "$(printf "%s\n" "$(readlink -f "$1")" | awk '{print tolower($0)}')" in
    *.arm) armcat "$1" | jq . ;;
	*.avi|*.mp4|*.wmv|*.dat|*.3gp|*.ogv|*.mkv|*.mpg|*.mpeg|*.vob|*.fl[icv]|*.m2v|*.mov|*.webm|*.ts|*.mts|*.m4v|*.r[am]|*.qt|*.divx)
		[ ! -f "${CACHE}.jpg" ] && \
			ffmpegthumbnailer -i "$1" -o "${CACHE}.jpg" -s 0 -q 5
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		;;
	*.bmp|*.jpg|*.jpeg|*.png|*.xpm|*.webp|*.gif|*.jfif)
		image "$1" "$2" "$3" "$4" "$5"
		;;
	#*.cbz|*.cbr|*.cbt)
		#[ ! -f "$CACHE" ] && \
			#comicthumb "$1" "$CACHE" 1024
		#image "$CACHE" "$2" "$3" "$4" "$5"
		#;;
    #*.doc) catdoc "$1" ;;
	#*.docx) docx2txt "$1" - ;;
	#*.epub)
		#[ ! -f "$CACHE" ] && \
			#epub-thumbnailer "$1" "$CACHE" 1024
		#image "$CACHE" "$2" "$3" "$4" "$5"
		#;;
	#*.html)
		#[ ! -f "$CACHE" ] && \ 
			#wkhtmltopdf "$1" - | pdftoppm -jpeg -f 1 -singlefile - "$CACHE"
		#image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		#;;
	*.html)
        lynx -width="$4" -display_charset=utf-8 -dump "$1"
        ;;
	*.ino)
		batorcat --language=cpp "$1"
		;;
    *.iso) iso-info --no-header -l "$1" ;;
    *.md) batorcat "$1" ;;
    *.o) nm "$1";;
    *.otf|*.ttf|*.woff|*.woff2)
        ~/.config/lf/preview-font "$1"
        image "/tmp/lf_fontpreview.png" "$2" "$3" "$4" "$5" 
        ;;
    #*.odt|*.ods|*.odp|*.sxw) odt2txt "$1" ;;
	*.pdf)
		[ ! -f "${CACHE}.jpg" ] && \
			pdftoppm -jpeg -f 1 -singlefile "$1" "$CACHE"
		image "${CACHE}.jpg" "$2" "$3" "$4" "$5"
		;;
    *.rar) unrar l "$1" ;;
    *.tar) tar tf "$1" ;;
	*.tar.bz2|*.tbz2) tar tjf "$1" ;;
	*.tar.txz|*.txz) xz --list "$1" ;;
    *.tgz|*.tar.gz) tar tzf "$1" ;;
    *.torrent) transmission-show "$1" ;;
    *.wav|*.mp3|*.flac|*.m4a|*.wma|*.ape|*.ac3|*.og[agx]|*.spx|*.opus|*.as[fx]|*.mka)
        exiftool "$1"
        ;;
    #*.xls|*.xlsx)
	*.zip|*.jar|*.war|*.ear|*.oxt) unzip -l "$1" ;;
	*.7z) 7z l "$1" ;;
	*.[1-8]) man "$1" | col -b ;;
		#ssconvert --export-type=Gnumeric_stf:stf_csv "$1" "fd://1" | batorcat --language=csv
		#;;
	*) batorcat "$1" ;;
esac
exit 1
