#!/bin/sh
if [ "$TERM" = "xterm-kitty" ]; then
    kitty +kitten icat --clear --stdin no --silent --transfer-mode file < /dev/null > /dev/tty
# elif [ -n "$FIFO_UEBERZUG" ]; then
# 	printf '{"action": "remove", "identifier": "PREVIEW"}\n' > "$FIFO_UEBERZUG"
fi
