#!/bin/sh

FONT=$1

SIZE=600x400
BG_COLOR="#050505"
FG_COLOR="#f0f0f0"
POSITION="+0+0"
FONT_SIZE=48
PREVIEW_TEXT="ABCDEFGHIJKLM\nNOPQRSTUVWXYZ\nabcdefghijklm\nnopqrstuvwxyz\n1234567890\n!@$\%(){}[]"
#FONTPREVIEW_DIR="$(mktemp -d "${TMPDIR:-/tmp}/lf_fontpreview.XXXXXXXX")" || exit
FONTPREVIEW_DIR="/tmp"
FONT_PREVIEW="$FONTPREVIEW_DIR/lf_fontpreview.png"

pre_exit() {
  kill -9 "$(cat "$PIDFILE" 2>/dev/null)" >/dev/null
  #rm -rf "$FONTPREVIEW_DIR"
  #rm -f $FONT_PREVIEW
}

generate_font_preview() {
  convert -size $SIZE xc:"$BG_COLOR" -gravity center -pointsize $FONT_SIZE -font "$1" -fill "$FG_COLOR" -annotate "$POSITION" "$PREVIEW_TEXT" -flatten "$2"
}

trap pre_exit EXIT
generate_font_preview "$FONT" "$FONT_PREVIEW"
