alias lf='$HOME/.config/lf/lfrun'
alias lynx='lynx -cfg $HOME/.config/lynx/lynx.cfg'
alias mpv='i3-swallow mpv'
alias sxiv='i3-swallow sxiv'

alias alacritty-theme='python $HOME/.config/alacritty/alacritty-theme.py $@'
alias calc='bc -q $@'
alias chat='mcabber'
alias cheat='cht.sh'
alias contacts='khard'
alias email='neomutt'
alias gist='gh gist'
alias img='vimiv'
alias notify='notify-send'
alias pdf='zathura'
alias screenshot='scrot -u $SCREENSHOTS/screenshot-%Y_%m_%d_%H_%M.png'
alias screen-off='xset dpms force off'
alias weather='curl -L wttr.in'
alias web='lynx'

alias '?'='duckduckgo'
alias bc="bc -ql"
alias ext='extract'
alias fm='lf'
alias tt='taskwarrior-tui'
alias tw='task'
alias tx='tmux'
alias ultraviolet='$EDITOR -c "VimwikiIndex"'
alias v='$EDITOR' 
alias vv='$EDITOR .'
alias x='extract'
alias ytdl='yt-dlp'

alias closure-stylesheets='java -jar $HOME/sdk/closure-stylesheets.jar'
alias krom='$ARMSDK/Krom/Krom $@'
alias lessc-live='neko $DEV/tool/lessc-live/lessc-live.n $@'
alias luamake='$HOME/src/lua-language-server/3rd/luamake/luamake $@'
alias ytdl-audio='ytdl --ignore-errors --output "%(title)s.%(ext)s" --extract-audio --audio-format mp3 "$@"'

#alias armory='blender -b --python $ARMSDK/armory/armory-cli.py $1'
#alias armory='blender -b $@ --python $ARMSDK/armory/armory-cli.py'
#alias armory='python $ARMSDK/armory/armory-cli.py $@'
#alias armory='blender --app-template armory $@'alias v="$EDITOR $@"
