exec-once = mako
exec-once = waybar

exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# exec-once = hyprpaper
exec-once = hypridle

exec-once = kitty
