#alias dev='cd $DEV;exa'
#alias disktree='cd $DT;exa'
alias downloads='cd $XDG_DOWNLOADS;exa'
alias music='cd $XDG_MUSIC_DIR;exa'
#alias work='cd $HOME/work;task +work $@'
alias video='cd $XDG_VIDEOS_DIR;exa'

alias alacritty-theme='python $HOME/.config/alacritty/alacritty-theme.py $@'
alias cal='cal -m'
alias calc='bc -q $@'
alias chat='profanity'
alias cheat='cht.sh'
alias chmox='chmod +x'
alias contact='khard'
alias contacts='khard'
alias dirsize='du'
#alias diskspace='du -S | sort -n -r | more'
alias email='neomutt'
alias ffmpeg="ffmpeg -hide_banner"
alias gist='gh gist'
alias getip='curl http://getip.disktree.net; echo'
alias icat="kitty +kitten icat"
alias img='swayimg'
#alias img='vimiv'
#alias ka='killall'
# alias keymap='i3-swallow sxiv $HOME/doc/keymap.png'
alias keymap='sxiv $HOME/doc/keymap.png'
alias lf='$HOME/.config/lf/lfrun'
alias lynx='lynx -vikeys -accept_all_cookies'
#alias logout='xfce4-session-logout --logout'
alias lock='waylock'
alias notify='notify-send'
alias open='xdg-open'
alias pdf='zathura'
#alias screenshot='scrot -u $SCREENSHOTS/screenshot-%Y_%m_%d_%H_%M.png'
#alias screen-off='xset dpms force off'
alias ultraviolet='cd $ULTRAVIOLET && nvim -c "VimwikiIndex"'
alias weather='curl -L wttr.in'
alias wtri='hl $HOME/dev/lib/wtri/wtri.hl'
alias wtric='$HOME/dev/lib/wtri/wtri'
alias ytdl='yt-dlp'
alias ytdl-mp3='yt-dlp --ignore-errors --output "%(title)s.%(ext)s" --extract-audio --audio-format mp3 "$@"'

alias cpuinfo='lscpu'
alias meminfo='free -m -l -t'
alias gpumeminfo='grep -i --color memory /var/log/Xorg.0.log'
alias gpuutilization='nvidia-smi --query-gpu=utilization.gpu --format=csv,noheader,nounits'

alias ip='ip addr show'
alias ports='netstat -tulanp' # List open tcp/udp ports
alias checkroute='mtr $1 -tez -Q1 --ipinfo 1'

#alias psmem='ps auxf | sort -nr -k 4'
#alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias flipper='$HOME/sdk/qFlipper-x86_64-1.2.2.AppImage'
alias reaper='$HOME/sdk/reaper/reaper'
alias vcvrack='(cd $HOME/sdk/vcvrack/ && ./Rack)'

alias blender-armory='blender3_3 --app-template armory'
#alias blender3_3='$HOME/sdk/blender-3.3.6/blender'
#alias armory-electron-runtime='/home/tong/dev/armory3d/armory_electron_runtime/armory-electron-runtime-linux-x64/armory-electron-runtime'
alias krom='$ARMSDK/Krom/Krom'
#alias khamake='node $ARMSDK/Kha/Tools/khamake/khamake.js'
alias khamake='$ARMSDK/nodejs/node-linux64 $ARMSDK/Kha/Tools/khamake/khamake.js'
alias kmake='$ARMSDK/Kha/Kinc/Tools/linux_x64/kmake'

alias a='archive'
alias az='archive zip'
alias bc="bc -ql"
alias ddg="ddgr"
alias ext='extract'
alias fm='lf'
alias g='git'
alias gg='lazygit'
alias j='exa'
alias jj='exa -l'
alias jl='exa -l'
alias ja='exa -a'
alias jja='exa -la'
alias jla='exa -la'
alias t='task'
alias tm='timew'
alias to='taskopen'
alias tt='taskwarrior-tui --report tui'
alias tx='tmux'
alias v='$EDITOR' 
alias vv='$EDITOR .'
alias x='extract'
alias '?'='ddg'

alias -s hxml='haxe'
alias -s js='node'

alias fchrome='fzf-chrome-history'
alias fscreenlayout='ls "$HOME/.local/share/screenlayout/" | fzf --prompt="  " | $@'

alias paci="pacman -Slq | fzf --multi --prompt ' ' --preview 'pacman -Si {1}' | xargs -ro sudo pacman -S"
alias pacr="pacman -Qq | fzf --multi --prompt ' ' --preview 'pacman -Qi {1}' | xargs -ro sudo pacman -Rns"

alias zconfig='cd $ZDOTDIR && $EDITOR .zshrc'
alias zreload='zshreload'
alias zsource='source $ZDOTDIR/.zshrc && source $HOME/.zshenv'
alias zstats='zshstats'

#alias closure-stylesheets='java -jar $HOME/sdk/closure-stylesheets.jar'
#alias lessc-live='neko $DEV/tool/lessc-live/lessc-live.n $@'
#alias luamake='$HOME/src/lua-language-server/3rd/luamake/luamake $@'

#alias clipcopy='cat "${1:-/dev/stdin}" | xsel --clipboard --input;'
#alias clippaste='xsel --clipboard --output;'


