#!/bin/bash
# Wallpaper management

[[ -z $WALLPAPERS ]] && WALLPAPERS="$HOME/.local/share/wallpaper/"
MODE="stretch"
OUT="$SCREEN"

random_file() {
    find "$1" -type f | shuf -n 1
}

while true; do
    case "$1" in
        path) echo "$WALLPAPERS"; exit 0 ;;
        select) IMG=$(i3-swallow sxiv -t -r -o "$WALLPAPERS"); break ;;
        random) IMG="random" break;;
        --image|-i) shift; IMG=$1; shift ;;
        --output|-o) shift; OUT=$1; shift ;;
        --mode|-m) shift; MODE=$1; shift ;;
        --wallpapers|-w) shift; WALLPAPERS=$1; shift ;;
        *) break;;
    esac
done
if [ -z "$IMG" ] || [ "$IMG" == "random" ]; then
    IMG=$(random_file "$WALLPAPERS")
fi
if [ -z "$OUT" ]; then
    xwallpaper --stretch --"$MODE" "$IMG"
else
    xwallpaper --output "$OUT" --"$MODE" "$IMG"
fi

