#!/bin/bash

wallpapers="$HOME/.local/share/wallpaper/"
mode="tile"
out="$SCREEN"

random_file() {
    find "$1" -type f | shuf -n 1
}

while true; do
    case "$1" in
        --random|-r) img=$(random_file "$wallpapers") shift;;
        --image|-i) shift; img=$1; shift ;;
        --output|-o) shift; out=$1; shift ;;
        --mode|-m) shift; mode=$1; shift ;;
        --wallpapers|-w) shift; wallpapers=$1; shift ;;
        *) break;;
    esac
done
if [ -z "$img" ] || [ "$img" == "random" ]; then
    img=$(random_file "$wallpapers")
fi
if [ -z "$out" ]; then
    xwallpaper --stretch --"$mode" "$img"
else
    xwallpaper --output "$out" --"$mode" "$img"
fi

