#!/bin/sh

font=$1

SIZE=532x365
BG_COLOR="#050505"
FG_COLOR="#f0f0f0"
POSITION="+0+0"
FONT_SIZE=38
PREVIEW_TEXT="ABCDEFGHIJKLM\nNOPQRSTUVWXYZ\nabcdefghijklm\nnopqrstuvwxyz\n1234567890\n!@$\%(){}[]"

#FONTPREVIEW_DIR="$(mktemp -d "${TMPDIR:-/tmp}/lf_fontpreview.XXXXXXXX")" || exit
FONTPREVIEW_DIR="/tmp"
FONT_PREVIEW="$FONTPREVIEW_DIR/lf_fontpreview.png"

pre_exit() {
    # Get the proccess ID of this script and kill it.
    # We are dumping the output of kill to /dev/null
    # because if the user quits sxiv before they
    # exit this script, an error will be shown
    # from kill and we dont want that
    kill -9 "$(cat "$PIDFILE" 2>/dev/null)" &> /dev/null

    #rm -rf "$FONTPREVIEW_DIR"
    #rm -f $FONT_PREVIEW
}

generate_preview() {
    convert -size $SIZE xc:"$BG_COLOR" -gravity center -pointsize $FONT_SIZE -font "$1" -fill "$FG_COLOR" -annotate +0+0 "$PREVIEW_TEXT" -flatten "$2"
}

trap pre_exit EXIT

generate_preview "$font" "$FONT_PREVIEW"


