#!/bin/sh

usage(){
    echo "Usage: decryptdir [dir-name to decrypt]"
    exit 1;
}

filename=$1

if [ ! $filename ] || [ $2 ] ;
  then
	  usage
fi

if [ $? -eq 0 ] ;
  then
    filename=(${1//./ });
fi

set +e
sslname="$filename.ssl_enc"
tarname="$filename.tar.gz"
if [ ! -e $sslname ] ;
  then
    echo "ERROR: \"$sslname\" does not exist or is wrong file type"
    exit 1;
fi

openssl aes-256-cbc -d -salt -pbkdf2 -in $sslname -out $tarname
if [ $? -ne 0 ];
  then
    echo "ERROR: could not decrypt \"$sslname\""
    exit 1;
fi

tar -xzf $tarname $filename
if [ $? -ne 0 ];
  then
    echo "ERROR: could not decompress \"$tarname\""
    exit 1;
fi
set -e

if [ -d $filename ] ;
  then
    rm $sslname
fi

rm $tarname
