#!/bin/sh

usage(){
    echo "Usage: encryptdir [dir-name to encrypt]"
    exit 1;
}

if [ $# -gt 2 ] || [ $# -eq 0 ];
    then
        usage
fi

if [ ! -d $1 ] ;
    then
        echo "ERROR: Directory \"$1\" does not exist"
        usage
        exit 1;
fi

if [ $1 == "." ] || [ $1 == ".." ] ;
    then
        echo "a set can't be a member of itself (no dot)"
        exit 1;
fi

lastChar="${1##${1%%?}}"
if [ "$lastChar" = "/" ];
    then
        echo "Please do not include \"/\" at the end of folder name"
        exit 1;
fi

foldername=$1
set +e
tarname="$1.tar.gz"
tar -czf $tarname $1
if [ $? -ne 0 ] ;
  then
     echo "ERROR: could not compress \"$tarname\""
    exit 1;
fi

sslname="$1.ssl_enc"
openssl aes-256-cbc -salt -pbkdf2 -in $tarname -out $sslname
if [ $? -ne 0 ] ;
  then
    echo "ERROR: could not encrypt \"$sslname\""
    rm $tarname
    exit 1;
fi
set -e

if [ -a $sslname ] ;
  then
    rm -rf $foldername
fi

rm $tarname
