#!/bin/sh
num=`task active | wc -l`
if [ $num -gt "1" ]
  then
    task_info=`task active | tail -n +4 | head -n -2`
    echo $task_info
    notify-send "$task_info"
    #canberra-gtk-play --file=/usr/share/sounds/gnome/default/alerts/drip.ogg
  else
    notify-send "No Active Tasks" "What are you doing?" 
    #canberra-gtk-play --file=/usr/share/sounds/ubuntu/stereo/dialog-question.ogg
fi
