name: shellcheck

on:
  push:
  pull_request:

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Shellcheck
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: .
          severity: error
