name: shellcheck

on:
  push:
    paths:
      - 'script/**'

jobs:
  shellcheck:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Shellcheck
        uses: ludeeus/action-shellcheck@1.1.0
        with:
          scandir: './script'
          severity: error
